### PR TITLE
Split getters and setters into big and little endian. Change PureScript

### PR DESCRIPTION
**Pull request by zaquest**
type for Uint32 operations to Int53.

### CODE REVIEW

**Comment by jacereda** [comment]
Looks good, but I would keep the big-endian names without suffix to avoid bumping the major version.

**Comment by jacereda** [comment]
On a second though, the `UInt32` fetcher was quite silly with an `Int` return type, so maybe we should bump.

**Comment by zaquest** [comment]
I've written [this package](https://pursuit.purescript.org/packages/purescript-uint/0.1.0/docs/Data.UInt). It provides exactly the `UInt32` type, maybe it could be used instead of `Int53`. It's poorly documented though - I'm not good at English. But I'll try adopting some more of docstrings from `purescript-int-53` later.

**Comment by jacereda** [comment]
Sounds good, I guess it's more appropriate here than the -int53 package.

**Comment by jacereda** [comment]
The changes to use Data.UInt are in the zaquest-int53_and_endianness, waiting for the -quickcheck/-transformers fix to merge to master.

**Comment by jacereda** [comment]
Should be merged now, thanks!

**Pull request merged**
