### PR TITLE
Removes external fail-able dependencies

### PR DESCRIPTION
**Pull request by AlexaDeWit**
In response to #20 and #19 

This pull request removes all dependencies to external NPM packages, as well as a dependency to node in the form of a require to util.

Another library will be released to provide this functionality elsewhere, and this PR will be updated to include that. This fact should probably included in the release notes.

Also I bumped the package.json version to 9, since it is included here and I assume that would be the version number associated here.

### CODE REVIEW

**Comment by AlexaDeWit** [comment]
In retrospect, my deriving library will depend on this version, and thus a release will be needed before that.

I'm not sure the best way to inform users of the API breaking change, but I think a release is warranted first, and I should have the new version ready pretty soon.

**Comment by AlexaDeWit** [comment]
Can you by chance email me when the v9 release goes through?

I will need to do major release updates to several other libraries I maintain, so it's best I notice asap

<3

**Comment by jacereda** [comment]
Sure, just waiting until @athanclark decides what primitives would be needed on his side, I'll make sure to notify you.

**Comment by AlexaDeWit** [comment]
Thanks, really appreciate that.

**Comment by athanclark** [comment]
I just finished verifying everything. I've got a few cosmetic considerations (argument placing to match intuitive formats, for instance, in `foldr`), and one semantic one - javascript's `foo.subarray(..)` method isn't semantically consistent - I'm going to make this library's implementation semantically consistent and dual to `slice` for end-users.

I'm trying to get this PR published today - the tests are pretty much total, and they've already exposed a number of bugs.

**Edit**: Just published: #23

**Comment by AlexaDeWit** [comment]
Closing this PR as the work it introduces is duplicated by #23 

Thanks Athan!

**Pull request closed without merging**
